### ISSUE TITLE
Presentaciones

### ISSUE THREAD

**Issue by BenjaPases** [lmdiazangulo/MCFNL2022#3]
Hola, los compañeros de la asignatura hemos estado hablando de cambiar la fecha de las presentaciones a la semana del 9 de mayo. Habría algún problema?. Gracias

**Comment by lmdiazangulo** [comment]
No, está bien. Entiendo que serían el martes y miércoles de esa semana. ¿Es así?

**Comment by BenjaPases** [comment]
Sí, en horario normal de clase.

**Comment by lmdiazangulo** [comment]
De acuerdo.
